server:
  port: 8004

spring:
  application:
    name: cloud-provider-payment8004
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      # mysql驱动包 com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud2020?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.zt.springcloud.entities  # 所有Entity别名类所在包
